from rasa_addons.nlu.components.language_setter import LanguageSetter
from rasa_addons.nlu.components.fuzzy_gazette import FuzzyGazette
from rasa_addons.nlu.components.entities_filter import EntitiesFilter
from rasa_addons.nlu.components.sweeper import Sweeper
from rasa_addons.nlu.components.duckling_crf_merger import DucklingCrfMerger
from rasa_addons.nlu.components.duckling_http_extractor import DucklingHTTPExtractor
from rasa_addons.nlu.components.entity_synonyms_endpoints import EntitySynonymBegin, EntitySynonymEnd
from rasa_addons.nlu.components.activity_logger import ActivityLogger
from rasa_addons.nlu.components.http_logger import HttpLogger
from rasa_addons.nlu.components.spell_check import BingSpellCheck